name: irsalmail-webmail

services:
  irsalmail-webmail:
    image: ghcr.io/quantitive-engineering/irsal-webmail:latest
    container_name: irsalmail-webmail
    restart: unless-stopped

    environment:
      - TZ=Asia/Muscat
      - JMAP_SERVER_URL=https://mail.irsal.cloud
      - APP_NAME=IrsalMail
      - APP_SHORT_NAME=Irsal
      - APP_DESCRIPTION=Enterprise Communication, Reimagined
      - FAVICON_URL=/branding/irsal-favicon.ico
      - PWA_ICON_URL=/branding/irsal-icon.svg
      - PWA_THEME_COLOR=#26a269
      - PWA_BACKGROUND_COLOR=#f7f7f8
      - APP_LOGO_LIGHT_URL=/branding/irsal-logo-color.svg
      - APP_LOGO_DARK_URL=/branding/irsal-logo-dark.svg
      - LOGIN_LOGO_LIGHT_URL=/branding/irsal-login-logo-color.svg
      - LOGIN_LOGO_DARK_URL=/branding/irsal-login-logo-dark.svg
      - LOGIN_COMPANY_NAME=IrsalMail
      - LOGIN_WEBSITE_URL=https://irsal.cloud
      - LOGIN_PRIVACY_POLICY_URL=https://irsal.cloud/privacy
      - LOGIN_SHOW_VERSION=false
      - STALWART_FEATURES=true
      - BULWARK_TELEMETRY=off
      - BULWARK_UPDATE_CHECK=off

    volumes:
      - /opt/irsalmail/webmail:/app/data

    ports:
      - 3000:3000
